apiVersion: v1
kind: Service
metadata:
  name: billetterie-service
spec:
  selector:
    app: billetterie
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
